src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\File", mappedBy="product", orphanRemoval=true, cascade={"remove", "persist"})
     * @Assert\Valid()
     */
    private $files;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isOffLinePayed;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="products")
     */
    private $user;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\OrphanUser", inversedBy="product", cascade={"persist", "remove"})
     */
    private $orphanUser;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $state;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Bill", mappedBy="product",orphanRemoval=true, cascade={"remove"})
     */
    private $bill;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Devis", mappedBy="product",orphanRemoval=true, cascade={"remove"})
     */
    private $devis;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $paymentIntent;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isStripePayed;

    /**
     * @ORM\OneToMany(targetEntity="Livrable", mappedBy="product", orphanRemoval=true ,cascade={"remove"})
     */
    private $livrables;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creationDate;

    public function __construct()
    {
        $this->files = new ArrayCollection();
        $this->setIsOffLinePayed(false);
        $this->setIsStripePayed(false);
        $this->setState('En attente');
        $this->livrables = new ArrayCollection();
        $this->setCreationDate(new \DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|File[]
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setProduct($this);
        }

        return $this;
    }

    public function removeFile(File $file): self
    {
        if ($this->files->contains($file)) {
            $this->files->removeElement($file);
            // set the owning side to null (unless already changed)
            if ($file->getProduct() === $this) {
                $file->setProduct(null);
            }
        }

        return $this;
    }

    public function getIsOffLinePayed(): ?bool
    {
        return $this->isOffLinePayed;
    }

    public function setIsOffLinePayed(bool $isOffLinePayed): self
    {
        $this->isOffLinePayed = $isOffLinePayed;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getOrphanUser(): ?OrphanUser
    {
        return $this->orphanUser;
    }

    public function setOrphanUser(?OrphanUser $orphanUser): self
    {
        $this->orphanUser = $orphanUser;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * @example En attente || Validée || Commencée || Terminée
     * @return string || null
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(?string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getBill(): ?Bill
    {
        return $this->bill;
    }

    public function setBill(?Bill $bill): self
    {
        $this->bill = $bill;

        if(null===$bill) return $this;

        // set the owning side of the relation if necessary
        if ($this !== $bill->getProduct()) {
            $bill->setProduct($this);
        }

        return $this;
    }

    public function getDevis(): ?Devis
    {
        return $this->devis;
    }

    public function setDevis(?Devis $devis): self
    {
        $this->devis = $devis;

        if(null === $devis) return $this;

        // set (or unset) the owning side of the relation if necessary
        $newProduct = $devis === null ? null : $this;
        if ($newProduct !== $devis->getProduct()) {
            $devis->setProduct($newProduct);
        }

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPaymentIntent(): ?string
    {
        return $this->paymentIntent;
    }

    public function setPaymentIntent(?string $paymentIntent): self
    {
        $this->paymentIntent = $paymentIntent;

        return $this;
    }

    public function getIsStripePayed(): ?bool
    {
        return $this->isStripePayed;
    }

    public function setIsStripePayed(bool $isStripePayed): self
    {
        $this->isStripePayed = $isStripePayed;

        return $this;
    }

    /**
     * @return Collection|Livrable[]
     */
    public function getLivrables(): Collection
    {
        return $this->livrables;
    }

    public function addLivrable(Livrable $livrable): self
    {
        if (!$this->livrables->contains($livrable)) {
            $this->livrables[] = $livrable;
            $livrable->setProduct($this);
        }

        return $this;
    }

    public function removeLivrable(Livrable $livrable): self
    {
        if ($this->livrables->contains($livrable)) {
            $this->livrables->removeElement($livrable);
            // set the owning side to null (unless already changed)
            if ($livrable->getProduct() === $this) {
                $livrable->setProduct(null);
            }
        }

        return $this;
    }

    /**
     * @param Product $product
     * @return bool
     */
    public function getIsPayable()
    {
        if($this->getState() === ('En attente')) {

             return false;
        }

        return true;
    }

    /**
     * @param Product $product
     * @param $oldState
     * @return bool
     */
    public function getIsFinished($oldState)
    {
        if($this->getState() === 'Terminée') {

            if ($oldState != 'Terminée') {
                return true;
            }

            return false;
        }

        return false;
    }

    /**
     * @param string $oldState
     * @return bool
     */
    public function getIsValidated(string $oldState)
    {
        if($this->getState() != 'En attente') {

            if ($oldState === 'En attente') {
                return true;
            }

            return false;
        }

        return false;
    }

    /**
     * @return bool
     */
    public function getIsPayed()
    {
        if ($this->getIsOffLinePayed() || $this->getIsStripePayed()) {

            return true;
        }

        return false;
    }

    public function getIsValid()
    {
        if ($this->getState() !== 'En attente') return true;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creationDate;
    }

    public function setCreationDate(\DateTimeInterface $creationDate): self
    {
        $this->creationDate = $creationDate;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use App\Form\eventListener\AdminProductSuscriber;
use App\Form\eventListener\ValidatedProductSuscriber;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;

class ProductType extends AbstractType
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('comment', TextareaType::class, [
                'label' => 'Commentaire',
                'attr' => [
                    'placeholder' => 'Commentaires'
                ]
            ])
            ->add('files', CollectionType::class, [
                'label' => 'Fichiers à traduire',
                'required' => false,
                'by_reference' => false,
                'entry_type' => FileType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true
            ])
        ;

        if ($this->security->isGranted("ROLE_ADMIN")) {
            $builder->addEventSubscriber(new AdminProductSuscriber());
        }

        /*
         * DELETE FIELDS IF PRODUCT ALREADY VALIDATED
         */
        $builder->addEventSubscriber(new ValidatedProductSuscriber());

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use App\Service\FileService;
use App\Service\MailService;
use App\Service\ProductService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class ProductController extends AbstractController
{
    public function show(Product $product, ProductService $productService): Response
    {
        if(!$productService->checkPermission($product)) return $this->redirectToRoute('home');

        return $this->render('product/show.html.twig', [
            'product' => $product,
        ]);
    }

    public function edit(Request $request, Product $product, FileService $fileService, ProductService $productService, MailService $mailService)
    {
        if(!$productService->checkEditable($product)) return $this->render("product/show.html.twig", ['product' => $product]);

        if(!$productService->checkPermission($product)) return $this->redirectToRoute('home');

        $form = $this->createForm(ProductType::class, $product);

        $oldstate = $product->getState();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            foreach ($product->getFiles() as $file) {
                if($fileService->saveFile($file) === false){
                    $product->removeFile($file);
                };
            }

            foreach ($product->getLivrables() as $file) {
                if(!$fileService->saveFile($file)){
                    $product->removeFile($file);
                };
            }

            if ((!$product->getPrice() || !$product->getDevis() ) && $product->getIsValid()) {
                $product->setState('En attente');

                $form->addError(new FormError('Vous ne pouvez pas valider une commande sans mettre de prix et un devis.'));

                return $this->render('product/edit.html.twig', [
                    'product' => $product,
                    'form' => $form->createView(),
                ]);
            }

            if($product->getIsValidated($oldstate)) {
                $this->addFlash('success', 'La commande a été validée, un mail a été envoyé au client.');

                $mailService->sendIsValidatedMail($product);
            }

            if($product->getIsFinished($oldstate)) {
                $this->addFlash('success', 'La commande est terminée, un mail de notification a été envoyé !');

                $mailService->sendIsFinishedMail($product);
            }

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('app_userspace_showproduct', [
                'product' => $product->getId(),
            ]);
        }

        return $this->render('product/edit.html.twig', [
            'product' => $product,
            'form' => $form->createView(),
        ]);
    }

    public function delete(Request $request, Product $product, ProductService $productService): Response
    {
        if(!$productService->checkEditable($product)) return $this->render("product/show.html.twig", ['product' => $product]);

        if($product->getIsPayed()) {
            $this->addFlash("warning", "Vous ne pouvez pas supprimer une commande déjà payée.");

            return $this->render("product/show.html.twig", ['product' => $product]);
        }

        if ($this->isCsrfTokenValid('delete'.$product->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($product);
            $entityManager->flush();

            $this->addFlash("success", "Commande supprimée !");
        }

        return $this->redirectToRoute('home');
    }
}

templates/product/_delete_form.html.twig
{% if product.state == "En attente" or is_granted("ROLE_ADMIN") %}
    <form method="post" action="{{ path('app_userspace_deleteproduct', {'product': product.id}) }}" onsubmit="return confirm('Vous êtes certain(e) de vouloir supprimer cette commande?');">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ product.id) }}">
        <button class="btn btn-danger">Supprimer la commande</button>
    </form>
{% endif %}

templates/product/_form.html.twig
{{ form_start(form, {'attr': { 'class' : 'col-12 row flex-column justify-content-center align-items-center' }}) }}

    <div class="form-group text-danger">
        {{ form_errors(form) }}
    </div>

    {% if is_granted("ROLE_ADMIN") %}
        {% if form.isOffLinePayed is defined %}
            <div class="form-group row flex-column align-content-baseline justify-content-center col-lg-6 col-md-4">
                {{ form_row(form.isOffLinePayed, {'attr' :{'class': 'form-control' }}) }}
            </div>
        {% endif %}

        <div class="form-group row flex-column align-content-baseline justify-content-center col-lg-6 col-md-4">
            {{ form_row(form.state, {'attr' :{'class': 'form-control' }}) }}
        </div>

        <div class="form-group row flex-column align-content-baseline justify-content-center col-lg-6 col-md-4">
            {% if product.isValid %}
                <p>Prix : {{ product.price }}</p>
            {% else %}
                {{ form_row(form.price, {'attr' :{'class': 'form-control' }}) }}
            {% endif %}
        </div>
    {% endif %}


    <div class="form-group col-8 text-center">
        <h3>{{ form_label(form.comment) }}</h3>
        {{ form_widget(form.comment, {'attr': {'class':'form-control'}}) }}
    </div>

    <div class="row justify-content-center align-items-center p-2 m-2">
        <h3 class="col-12 text-center">Fichiers & devis</h3>

        {% include('product/files.html.twig') %}

        {% include('product/devis.html.twig') %}
    </div>

    {% if is_granted('ROLE_ADMIN') %}
        <div class="row justify-content-center align-items-center p-2 m-2">
            <h3 class="col-12 text-center">Facture & livrables</h3>

            {% include('product/livrables.html.twig') %}

            {% include('product/facture.html.twig') %}
        </div>
    {% endif %}

    <div style="display:none">{{ form_rest(form) }}</div>

    <div class="form-group justify-content-center row col-12">
        <button type="submit" class="col-auto btn btn-success">Valider</button>
    </div>
{{ form_end(form) }}

{% block javascripts %}
    {{ encore_entry_script_tags('EmbedFiles') }}

    {% if is_granted('ROLE_ADMIN') %}
        {{ encore_entry_script_tags('EmbedLivrables') }}
    {% endif %}
{% endblock %}

templates/product/devis.html.twig
<div class="row justify-content-center align-items-center">
    <div id="devis" class="col-auto row p-2 m-1 border rounded justify-content-center">
        <h3 class="col-12 text-center">Devis</h3>
        {% if product.devis is not null %}
            <a class="col-auto" href="{{ path('app_userspace_downloaddevis', {'product' : product.id, 'devis' : product.devis.id}) }}"><button class="btn btn-success" type="button">{{ product.devis.name }}</button></a>
        {% else %}
            <p>Le devis n'est pas encore disponible</p>
        {% endif %}

        {% if product.devis is not null and is_granted('ROLE_ADMIN') %}
            <a id ="addDevis" class="col-12 text-center" href="{{ path('app_adminspace_uploaddevis', {'product': product.id}) }}">Changer le devis</a>
        {% elseif product.devis is null and is_granted('ROLE_ADMIN') %}
            <a id ="addDevis" class="col-12 text-center" href="{{ path('app_adminspace_uploaddevis', {'product': product.id}) }}">Ajouter un devis</a>
        {% endif %}
    </div>
</div>

templates/product/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Modifier une commande</h1>

    <div style="display: none" id="productId">{{ product.id }}</div>

    {{ include('product/_form.html.twig', {'button_label': 'Update'}) }}

    {{ include('product/_delete_form.html.twig') }}

    <div class="col-12">
        <a class="m-2" href="{{ path('app_userspace_showproduct', {'product': product.id}) }}">Retour sur le produit</a>
    </div>

    {{ include('product/returnToListButton.html.twig') }}

{% endblock %}

templates/product/editButton.html.twig
{% if not product.isValid or is_granted("ROLE_ADMIN") %}
    <a class="m-2" href="{{ path('app_userspace_editproduct', {'product': product.id }) }}"><button class="btn btn-warning">Modifier la commande</button></a>
{% endif %}

templates/product/facture.html.twig
<div id="facture" class="col-auto row p-2 m-1 border rounded text-center justify-content-center">
    <h3 class="col-12 text-center">Facture</h3>
    {% if product.bill is not null %}
        <a class="col-auto" href="{{ path('app_userspace_downloadbill', {'product' : product.id, 'bill' : product.bill.id}) }}"><button class="btn btn-success" type="button">{{ product.bill.name }}</button></a>
    {% else %}
        <p>La facture n'est pas encore disponible</p>
    {% endif %}

    {% if product.bill is not null and is_granted("ROLE_ADMIN") %}
        <a id ="addBill" class="col-12" href="{{ path('app_adminspace_uploadbill', {'product': product.id}) }}">Changer la facture</a>
    {% elseif product.bill is null and is_granted('ROLE_ADMIN') %}
        <a id ="addBill" class="col-12" href="{{ path('app_adminspace_uploadbill', {'product': product.id}) }}">Ajouter une facture</a>
    {% endif %}
</div>

templates/product/files.html.twig
{% if form.files is defined %}

    <div id="fichiers" class="col-auto row p-2 m-1 border rounded text-center justify-content-center">

        <h3>{{ form_label(form.files) }}</h3>
        <div class="files row col-12  flex-column align-items-center justify-content-center" data-prototype="{{ form_widget(form.files.vars.prototype)|e('html_attr') }}">

            {% for file in form.files %}
                <div class="row col-auto file justify-content-center align-items-center">
                    <div class="col text-right">{{ file.vars.value.name }}</div>
                    <button type="button" class="btn btn-danger delete"></button>

                    <div style="display:none">{{ form_widget(file) }}</div>
                </div>
            {% endfor %}
        </div>
    </div>

{% else %}

    <div id="fichiers" class="row justify-content-center align-items-center border rounded p-2 m-2">
        <h3 class="col-12 text-center">Fichiers</h3>

        {% for file in product.files %}
            <a class="m-2" href="{{ path('app_userspace_downloadfile', {'file' : file.id, 'product': product.id }) }}"><button class="btn btn-success">{{ file.name }}</button></a>
        {% else %}
            <p>Pas de fichiers</p>
        {% endfor %}
    </div>

{% endif %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Liste des commandes</h1>

    <table class="table">
        <thead>
        <tr>
            <th>ID</th>
            {% if is_granted("ROLE_ADMIN") %}
                <th>Client</th>
                <th></th>
            {% endif %}
            <th>Etat de la demande</th>
            <th>Paiement</th>
            <th>Prix</th>
            <th>Devis</th>
            <th>Facture</th>
            <th>Date de création</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
                <td>{{ product.id }}</td>

                {% if is_granted("ROLE_ADMIN") %}
                    {% if product.user %}
                        <td><a href="{{ path('app_adminspace_seeuser', {'user': product.user.id }) }}">{{ product.user.lastName }} {{ product.user.firstName }}</a></td>
                        {{ product.user ? '<td>Avec compte</td>' : '<td>Sans compte</td>' }}
                    {% else %}
                        <td><a href="{{ path('app_adminspace_orphanshow', {'id': product.orphanUser.id }) }}">{{ product.orphanUser.lastName }} {{ product.orphanUser.firstName }}</a></td>
                        {{ product.user ? '<td>Avec compte</td>' : '<td>Sans compte</td>' }}
                    {% endif %}
                {% endif %}

                <td>{{ product.state }}</td>
                <td>{{ product.isPayed ? 'Oui' : 'Non' }}</td>
                <td>{{ product.price ? product.price : ' / ' }}</td>
                <td>{{ product.devis ? 'Oui' : 'Non' }}</td>
                <td>{{ product.bill ? 'Oui' : 'Non' }}</td>
                <td>{{ product.creationDate|date("m/d/Y h:i") }}</td>
                <td>
                    {{ include('product/editButton.html.twig') }}
                </td>
                <td>
                    <a href="{{ path('app_userspace_showproduct', {'product': product.id }) }}"><button class="btn btn-primary">Voir</button></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/product/livrables.html.twig
{% if form.livrables is defined %}

    <div class="col-auto row p-2 m-1 border rounded text-center justify-content-center">

        <h3>{{ form_label(form.livrables) }}</h3>
        <div class="livrables row col-12  flex-column align-items-center justify-content-center" data-prototype="{{ form_widget(form.livrables.vars.prototype)|e('html_attr') }}">

            {% for livrable in form.livrables %}
                <div class="row col-auto file justify-content-center align-items-center">
                    <div class="col text-right">{{ livrable.vars.value.name }}</div>
                    <button type="button" class="btn btn-danger delete"></button>

                    <div style="display:none">{{ form_widget(livrable) }}</div>
                </div>
            {% endfor %}
        </div>
    </div>

{% else %}

    <div id="livrables" class="col-auto row p-2 m-1 border rounded text-center justify-content-center">
        <h3 class="col-12 text-center">Livrables</h3>
        {% for livrable in product.livrables %}
            <a href="{{ path('app_userspace_downloadlivrable', { 'livrable' : livrable.id, 'product' : product.id}) }}"><button class="btn btn-success">{{ livrable.name }}</button></a>
        {% else %}
            <p>Pas de fichiers</p>
        {% endfor %}
    </div>

{% endif %}

templates/product/new.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Création d'une nouvelle commande</h1>

    {{ include('product/_form.html.twig') }}

    {{ include('product/returnToListButton.html.twig') }}
{% endblock %}

templates/product/returnToListButton.html.twig
{% if is_granted("ROLE_ADMIN") %}
    <div class="col-12">
        <a class="m-2" href="{{ path('app_adminspace_products') }}"><button class="btn btn-primary">Retour sur la liste</button></a>
    </div>
{% endif %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Commande n°{{ product.id }}</h1>

    <table class="table col-lg-6 col-md-9 col-sm-12">
        <tbody>
        <tr>
            <th>Commande payée ?</th>
            <td>{{ product.isPayed ? 'Oui' : 'Non' }}</td>
        </tr>
        {% if product.isPayed %}
            <tr>
                <th>Type de paiement</th>
                {% if product.isStripePayed %}
                    <td>Paiement Stripe</td>
                {% elseif product.isOffLinePayed %}
                    <td>Paiement hors ligne</td>
                {% endif %}
            </tr>
        {% endif %}
        <tr>
            <th>Etat de la commande</th>
            <td>{{ product.state }}</td>
        </tr>
        <tr>
            <th>Création de la commande</th>
            <td>{{ product.creationDate | date("d/m/Y h:i")}}</td>
        </tr>
        <tr>
            <th>Prix</th>
            <td>{% if product.price %}
                {{ product.price }} €
                {% else %}
                    L'estimation n'est pas encore disponible.
                {% endif %}
            </td>
        </tr>
        </tbody>
    </table>

    <div class="col-12 row flex-column justify-content-center align-items-center p-2 m-2">
        <h3 class="col-lg-6 col-md-9 col-sm-12 text-center">Commentaire</h3>
        <p class="col-lg-6 col-md-9 col-sm-12 border rounded p-2 text-center">{{ product.comment }}</p>
    </div>


    <div class="row justify-content-center align-items-center p-2 m-2">
        <h3 class="col-12 text-center">Fichiers à traduire & devis</h3>

        {% include('product/files.html.twig') %}


        {% include('product/devis.html.twig') %}
    </div>

    <div class="row justify-content-center align-items-center p-2 m-2">
        <h3 class="col-12 text-center">Facture & livrables</h3>
        {% if product.isPayed or is_granted('ROLE_ADMIN') %}

            {% include('product/facture.html.twig') %}

            {% include('product/livrables.html.twig') %}

        {% else %}
            <p>Vous devez régler la commande pour avoir accès aux livrables et à la facture</p>
        {% endif %}
    </div>

    {{ include('product/editButton.html.twig') }}

    {% if not product.isPayed  and not is_granted('ROLE_ADMIN') and product.isValid %}
        {# <a id="OnlinePaymentButton" class="m-2" href="{{ path('app_stripe_redirecttocheckout', {'id': product.id}) }}"><button class="btn btn-primary">Payer en ligne</button></a> #}
        <button id="OnlinePaymentButton" data-product="{{ product.id }}" class="btn btn-primary">Payer en ligne avec Stripe</button>
        <img style="display: none" alt="loading icon" src="{{ asset('build/images/Loading_icon .gif') }}" id="ajax-loading">
    {% endif %}

    {{ include('product/returnToListButton.html.twig') }}
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('StripeApi') }}
{% endblock %}